app_name: "Html2Dita Backend (FastAPI)"
port: 8001
base: "http://localhost:8001"
mongodb_uri: "mongodb://localhost:27017"
mongodb_db: "htmltodita"
input_root: "input"
output_root: "output"
downloads_root: "downloads"